version: "3.8"

services:
  app:
    build: .
    container_name: metrics-monitor
    ports:
      - "8888:8888"
    environment:
      - DB_HOST=metrics-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=metrics_db
      - DB_PORT=5432
    depends_on:
      metrics-db:
        condition: service_healthy
    entrypoint: >
      sh -c "until pg_isready -h metrics-db -p 5432 -U postgres; do sleep 2; done && ./metrics-monitor"
    stop_signal: SIGINT
    stop_grace_period: 30s

  metrics-db:
    image: postgres:15-alpine
    container_name: metrics-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrics_db
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "metrics_db"]
      interval: 10s
      retries: 5
      start_period: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  pgdata:
