version: "3.8"

services:
  app:
    build: .
    container_name: metrics-monitor
    ports:
      - "8888:8888"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: metrics-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metrics_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
